# input your custom config here. it will overwrite the corresponding settings in default.yaml.
run: 
    mode: autoline
save: 
    en: True
    pub: 
        prefix: test1
        subdir: test
gpt: 
    model: 4t
autoline: 
    probset: 
        path: data/HDLBits/HDLBits_data.jsonl
        mutant_path: data/HDLBits/HDLBits_data_mutants.jsonl
        # more_info_paths: ['data/HDLBits/HDLBits_circuit_type.jsonl']
        # filter: [{'circuit_type': 'CMB'}]
        # exclude_json: "saves_inEDA/MLCAD/EXP1_more/TaistBench/NO_7_20240503_230146/Chatbench_RunInfo.json"
        only: ["mux2to1v"]
    promptscript: pychecker
    timeout: 40